AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Function - auth

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: auth-function
      Handler: auth::auth.Function::FunctionHandler
      Runtime: dotnet8
      MemorySize: 256
      Timeout: 10
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth
            Method: POST

Outputs:
  AuthFunctionEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth"